# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: notify-slack-new-channel

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'development'}
  region: ap-northeast-1
  environment: ${file(./config/${self:provider.stage}.yml)}

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  notify-slack-new-channel:
    handler: app/handler.notify_news
    events:
      - http:
          path: notify-slack-new-channel
          method: post

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
